name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Install dependencies
      run: dotnet restore
    - name: NPM Install
      run: npm install
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./PElshen.NoUiSlider.Blazor
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./PElshen.NoUiSlider.Blazor.Sample
    - name: Test
      run: dotnet test --no-restore --verbosity normal
