# This is a basic workflow to help you get started with Actions

name: Publish to Nuget

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Publish NuGet
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: PElshen.NoUiSlider.Blazor/PElshen.NoUiSlider.Blazor.csproj
          # NuGet package id, used for version detection & defaults to project name
          PACKAGE_NAME: NoUiSlider.Blazor
          NUGET_KEY: ${secrets.NUGET_API_KEY_INT}
          # NuGet server uri hosting the packages, defaults to https://api.nuget.org
          NUGET_SOURCE: https://apiint.nugettest.org/v3/index.json
